### ISSUE TITLE
mobile phone problems

### ISSUE THREAD

**Issue by alibbz1** [Leiren/Npanel#2]
Hello my friend, one of the problems I have is that it is not possible to connect to the control panel with a mobile phone because access to the keyboard is blocked.  Also, the control panel does not support the mobile version, it would be very good if this problem is solved

**Comment by Leiren** [comment]
yes i am aware of it, will be fixed soon.

**Comment by Leiren** [comment]
I tested some methods and it looks like I can't trigger the phone's native keyboard. The browser manages it automatically on regular html input elements.

since this ui runs on a canvas element, there is currently no way to trigger the keyboard, even with experimental chrome apis;



So,

The plan is to implement a virtual keyboard for that and also work on some widgets size to fit the screen, since there is no bootstrap lib for ImGui :(



I will probably focus on a server side feature (nodes or http reverse proxy for user-made websites).

Then we come back to this, since optimizing the ui for phones is not a priority right now.

**Comment by alibbz1** [comment]
Thank you my friend for your continuous efforts to access the free internet and I wish you success

**Comment by Leiren** [comment]
You are welcome,
Thanks for helping me on improving this project.

**Comment by Leiren** [comment]
A basic keyboard is now available in version (0.1.9) i have tested basic features and it (at least) allows the admin to login & edit users
