### ISSUE TITLE
error on server status

### ISSUE THREAD

**Issue by alibbz1** [Leiren/Npanel#4]
Hello, my friend is giving this error after the update and the speed has dropped drastically 
![IMG_20230214_214523_943](https://user-images.githubusercontent.com/32574960/218823431-d3267ac2-65ff-4f54-8b1e-306d79d63621.jpg)
![IMG_20230214_214534_275](https://user-images.githubusercontent.com/32574960/218823450-6f4b50e7-0747-4c1e-af88-ead6dcc37eb6.jpg)

**Comment by Leiren** [comment]
This is not Npanel logs , 
There are trojan-go logs and are normal, there is no problem, it just says Error when trojan-go finds a website visitor instead of a vpn connect handshake. 
so you should ignore them since those logs are not actually counted as errors. only a log with [FATAL] is a real error and terminates the server side.

**Comment by Leiren** [comment]
The speed drop however, is not related to Npanel because i did not change anything related to backend in recent versions. 

the problem should be something else, i will test connection speed from china and if i found any difference between versions, i will write it here

**Comment by Leiren** [comment]
since past 3 versions , there was no speed difference as expected

**Comment by alibbz1** [comment]
Thank you, my friend, for following up on this matter, probably the problem is with the internal network in Iran, where the bandwidth is severely reduced
